import "@/styles/globals.css";
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import Providers from "./Providers";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
	title: "Best TV Shows",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={inter.className}>
			<body>
				<Providers>
					<Header />
					<NavBar />
					{children}
				</Providers>
			</body>
		</html>
	);
}
